## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

## 2. Load Dataset

In [2]:
# Load the dataset into a pandas DataFrame
hospital_data = pd.read_csv('healthcare_dataset.csv')

## 3. Data Inspection

In [3]:
# Preview the first few rows to understand the structure of the dataset
hospital_data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [4]:
# Check the number of rows and columns in the dataset
hospital_data.shape

(55500, 15)

In [5]:
# Inspect the dataset structure, column names, non-null values, and data types
hospital_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [6]:
# Generate summary statistics for numerical columns
hospital_data.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [7]:
# Check for missing values across all columns
hospital_data.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [8]:
# Identify duplicate records in the dataset
hospital_data.duplicated().sum()

534

## 4. Data Cleaning & Preprocessing

In [9]:
# Remove duplicate rows to maintain data integrity
hospital_data = hospital_data.drop_duplicates()

In [10]:
# Confirm that duplicates have been removed
hospital_data.duplicated().sum()

0

In [11]:
# Verify the new dataset size after removing duplicates
hospital_data.shape

(54966, 15)

In [12]:
#Standardize text formatting in the 'Name' column by converting values to title case
hospital_data['Name'] = hospital_data['Name'].str.title()

In [13]:
# Preview dataset to confirm the changes
hospital_data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [14]:
# Convert admission and discharge date columns to datetime format
hospital_data['Date of Admission'] = pd.to_datetime(hospital_data['Date of Admission'])
hospital_data['Discharge Date'] = pd.to_datetime(hospital_data['Discharge Date'])

In [15]:
# Verify that the data types have been updated correctly
hospital_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  object
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  object
 3   Blood Type          54966 non-null  object
 4   Medical Condition   54966 non-null  object
 5   Date of Admission   54966 non-null  datetime64[ns]
 6   Doctor              54966 non-null  object
 7   Hospital            54966 non-null  object
 8   Insurance Provider  54966 non-null  object
 9   Billing Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission Type      54966 non-null  object
 12  Discharge Date      54966 non-null  datetime64[ns]
 13  Medication          54966 non-null  object
 14  Test Results        54966 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.7+ MB

## 5. Feature Engineering

In [16]:
# Create a new feature representing the patient's length of stay in the hospital
hospital_data['Length of Stay'] = (
    hospital_data['Discharge Date'] - hospital_data['Date of Admission']
).dt.days

In [17]:
# Preview the dataset to confirm the new column
hospital_data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20

In [18]:
# Add unique identifier - Patient_id
hospital_data['Patient_id'] = range(1, len(hospital_data)+1)
cols = ['Patient_id'] + [col for col in hospital_data.columns if col != 'Patient_id']
hospital_data = hospital_data[cols]

In [19]:
# Rename columns to snake_case before export
hospital_data.columns = [col.lower().replace(' ', '_') for col in hospital_data.columns]

In [20]:
# Preview first 5 rows of the cleaned data to verify all transformations
hospital_data.head()

,patient_id,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,length_of_stay
0,1,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,2,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,3,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15
3,4,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,5,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20

In [21]:
# Numeric adjustment before export
hospital_data['billing_amount'] = hospital_data['billing_amount'].round(2)

## 6. Export Cleaned Data

In [22]:
# Export the cleaned dataset for further analysis in SQL and Power BI
hospital_data.to_csv('cleaned_hospital_data.csv', index=False)